version: '3.7'

services:
    
    black_widow:
        build: './black_widow/'
        container_name: black_widow_dev
        hostname: black_widow_dev
        volumes:
            - type: volume
              source: black_widow_vol
              target: ${DESTINATION_APP}
        working_dir: ${DESTINATION_APP}
        command: /bin/bash -c "python3 MainServer.py"
        environment: 
            APP_ENV: "dev"
            APP_DEBUG: "False"
            APP_PORT: ${BW_APP_PORT}
            MONGODB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
        ports:
            - ${BW_CON_PORT}:${BW_APP_PORT}
        networks: 
            widow_net:
                ipv4_address: ${WIDOW_IP}
        stdin_open: true
        tty: true
    
    mongodb:
        build: './mongodb/'
        hostname: ${MONGODB_HOSTNAME}
        container_name: black_widowDB
        restart: always
        ports: 
            - ${MONGODB_PORT}-27019:${MONGODB_PORT}-27019

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_DATA_DIR: /data/db
            MONGODB_LOG_DIR: /dev/null
        volumes: 
            - type: volume
              source: mongodbdata
              target: /data/db
        
        networks: 
            widow_net:
                ipv4_address: ${MONGODB_IP}


    redis:
        build: './redis/'
        container_name: redis
        hostname: redis
        ports: 
            - ${REDIS_PORT}:${REDIS_PORT}
        networks: 
            widow_net:
                ipv4_address: ${REDIS_HOST}

    nextcloud_db:
        #image: postgres
        build: './nextcloud_db/'
        restart: always
        hostname: ${POSTGRES_HOST}
        container_name: ${POSTGRES_HOST}
        volumes:
            - nextcloud_db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
        networks: 
            nextcloud_net:
                ipv4_address: ${NEXTCLOUD_DB_IP}
                

    nextcloud:
        build: './nextcloud/'
        container_name: nextcloud
        hostname: nextcloud
        ports: 
            - "${NEXTCLOUD_PORT}:${NEXTCLOUD_APP_PORT}"
        volumes:
            - nextcloud:/var/www/html
        environment: 
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
            NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
  
        depends_on:
            - nextcloud_db

        networks: 
            nextcloud_net:
                ipv4_address: ${NEXTCLOUD_IP}
    
    
           
volumes:
    black_widow_vol:

        driver: local
        driver_opts: 
            type: none
            device: ${LOCAL_APP_PATH}
            o: 'bind'

    mongodbdata:
        driver: local


    nextcloud:
    nextcloud_db:

        
networks:
    widow_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_WIDOW}/24

    nextcloud_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_NEXTCLOUD}/24


            
        
