version: '3.7'

services:
    
    black_widow:
        build: './black_widow/'
        container_name: black_widow_dev
        hostname: black_widow_dev
        volumes:
            - type: volume
              source: black_widow_vol
              target: ${DESTINATION_APP}
        working_dir: ${DESTINATION_APP}
        command: /bin/bash -c "python3 MainServer.py"
        environment: 
            APP_ENV: "dev"
            APP_DEBUG: "False"
            APP_PORT: ${BW_APP_PORT}
            MONGODB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
        ports:
            - "${BW_CON_PORT}:${BW_APP_PORT}"
        networks: 
            widow_dev:
                ipv4_address: ${WIDOW_IP}
        stdin_open: true
        tty: true
    
    mongodb:
        build: './mongodb/'
        hostname: ${MONGODB_HOSTNAME}
        container_name: black_widowDB
        restart: always
        ports: 
            - ${MONGODB_PORT}-27019:${MONGODB_PORT}-27019

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_DATA_DIR: /data/db
            MONGODB_LOG_DIR: /dev/null
        volumes: 
            - type: volume
              source: mongodbdata
              target: /data/db
        
        networks: 
            widow_dev:
                ipv4_address: ${MONGODB_IP}


    redis:
        build: './redis/'
        container_name: redis
        hostname: redis
        ports: 
            - ${REDIS_PORT}:${REDIS_PORT}
        networks: 
            widow_dev:
                ipv4_address: ${REDIS_HOST}
        

    nextcloud:
        build: './nextcloud/'
        #image: nextcloud
        container_name: nextcloud
        hostname: nextcloud
        ports: 
            - 8081:80
        volumes:
            # - type: volume
            #   source: nextcloud_shared
            #   target: /var/www/html/data/admin/files
            - nextcloud:/var/www/html
        
            #- ./nextcloud/config.sample.php:/var/www/html/config/config.php
        environment: 
            - POSTGRES_HOST=nextcloud_db
            - POSTGRES_DB=files
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - NEXTCLOUD_ADMIN_PASSWORD=password
            - NEXTCLOUD_ADMIN_USER=admin
  
        depends_on:
            - nextcloud_db
#########
        #secrets:
        #    - nextcloud_admin_password
        #    - nextcloud_admin_user
        #    - postgres_db
        #    - postgres_password
        #    - postgres_user
        networks: 
            widow_dev:
                ipv4_address: "172.18.128.4"
    
    nextcloud_db:
        image: postgres
        restart: always
        hostname: nextcloud_db
        container_name: nextcloud_db
        volumes:
        - nextcloud_db:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=files
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_HOST=nextcloud_db
        #########
        #secrets:
        #- postgres_db
        #- postgres_password
        #- postgres_user
        networks: 
            widow_dev:
                ipv4_address: "172.18.128.5"


# secrets:
#     nextcloud_admin_password:
#         file: ./secrets/nextcloud_admin_password.txt # put admin password to this file
#     nextcloud_admin_user:
#         file: ./secrets/nextcloud_admin_user.txt # put admin username to this file
#     postgres_db:
#         file: ./secrets/postgres_db.txt # put postgresql db name to this file
#     postgres_password:
#         file: ./secrets/postgres_password.txt # put postgresql password to this file
#     postgres_user:
#         file: ./secrets/postgres_user.txt # put postgresql username to this file


           
volumes:
    black_widow_vol:

        driver: local
        driver_opts: 
            type: none
            device: ${LOCAL_APP_PATH}
            o: 'bind'

    mongodbdata:
        driver: local

    #uploaddata:
    #    driver: local
    #    driver_opts: 
    #        type: none
    #        device: ${UPLOAD_SERVER_PATH}
    #        o: 'bind'
        
    nextcloud:
    nextcloud_db:
    # nextcloud_shared: 
    #     driver: local
    #     driver_opts: 
    #         type: none
    #         device: /home/vagrant/Desktop/files
    #         o: 'bind'
      

        
networks:
    widow_dev:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_WIDOW}/24


            
        
