version: '3.7'

services:
    
    black_widow:
        build: './black_widow/'
        container_name: black_widow_dev
        hostname: black_widow_dev
        volumes:
            - type: volume
              source: black_widow_vol
              target: ${DESTINATION_APP}
        working_dir: ${DESTINATION_APP}
        command: /bin/bash -c "python3 MainServer.py"
        environment: 
            APP_ENV: "dev"
            APP_DEBUG: "False"
            APP_PORT: ${BW_APP_PORT}
            MONGODB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_HOSTNAME: ${MONGODB_HOSTNAME}
        ports:
            - ${BW_CON_PORT}:${BW_APP_PORT}
        networks: 
            widow_net:
                ipv4_address: ${WIDOW_IP}
        stdin_open: true
        tty: true
    
    mongodb:
        build: './mongodb/'
        hostname: ${MONGODB_HOSTNAME}
        container_name: black_widowDB
        restart: always
        ports: 
            - ${MONGODB_PORT}-27019:${MONGODB_PORT}-27019

        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
            MONGODB_DATA_DIR: /data/db
            MONGODB_LOG_DIR: /dev/null
        volumes: 
            - type: volume
              source: mongodbdata
              target: /data/db
        
        networks: 
            widow_net:
                ipv4_address: ${MONGODB_IP}

    
    redis:
        build: './redis/'
        container_name: redis
        hostname: redis
        ports: 
            - ${REDIS_PORT}:${REDIS_PORT}
        networks: 
            widow_net:
                ipv4_address: ${REDIS_HOST}

    nextcloud_db:
        build: './nextcloud_db/'
        restart: always
        hostname: ${POSTGRES_HOST}
        container_name: ${POSTGRES_HOST}
        volumes:
            - nextcloud_db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
        networks: 
            nextcloud_net:
                ipv4_address: ${NEXTCLOUD_DB_IP}


    nextcloud:
        build: './nextcloud/'
        container_name: nextcloud
        hostname: nextcloud
        ports: 
            - "${NEXTCLOUD_PORT}:${NEXTCLOUD_APP_PORT}"
        volumes:
            - nextcloud:/var/www/html
        environment: 
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
            NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
            NEXTCLOUD_TRUSTED_DOMAINS: 172.18.128.1
        depends_on:
            - nextcloud_db
        networks: 
            nextcloud_net:
                ipv4_address: ${NEXTCLOUD_IP}
    # guacd
    guacd:
        container_name: guacd_compose
        image: guacamole/guacd:1.0.0
        networks:
            guacnetwork_compose:
        #restart: always
        volumes:
            - ./drive:/drive:rw
            - ./record:/record:rw
    # postgres
    postgres:
        container_name: postgres_guacamole_compose
        environment:
            PGDATA: /var/lib/postgresql/data/guacamole
            POSTGRES_DB: guacamole_db
            POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
            POSTGRES_USER: guacuser
        image: postgres
        networks:
            guacnetwork_compose:
        #restart: always
        volumes:
            - ./init:/docker-entrypoint-initdb.d:ro
            - ./data:/var/lib/postgresql/data:rw

    # guacamole
    guacamole:
        container_name: guacamole_compose
        depends_on:
            - guacd
            - postgres
        environment:
            GUACD_HOSTNAME: guacd
            POSTGRES_DATABASE: guacamole_db
            POSTGRES_HOSTNAME: postgres
            POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
            POSTGRES_USER: guacuser
        image: guacamole/guacamole:1.0.0
        networks:
            guacnetwork_compose:
        ports:
            - 8085:8080/tcp

           
volumes:
    black_widow_vol:

        driver: local
        driver_opts: 
            type: none
            device: ${LOCAL_APP_PATH}
            o: 'bind'

    mongodbdata:
        driver: local


    nextcloud:
    nextcloud_db:

        
networks:
    widow_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_WIDOW}/24
    

    nextcloud_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_NEXTCLOUD}/24
    
    guacnetwork_compose:
        driver: bridge


            
        
