Vagrant.configure("2") do |config|
	config.vm.define "victim" do |victim|
		victim.vm.hostname = "victim"
		victim.vm.box = "generic/alpine37"
		victim.vm.network "private_network", ip: "192.168.50.6", virtualbox__intnet: true
		victim.vm.synced_folder "./host_shared_folder", "/guest_shared_folder" 
		victim.vm.provision "shell", inline: <<-SHELL
			pip install unique-id
		SHELL
	end
	config.vm.provider "virtualbox" do |vb|
		vb.name = "victim"
		vb.gui = false
		vb.memory = "1024"
		vb.cpus = "2"
	end
end
