Vagrant.configure("2") do |config|
	config.vm.define "attacker" do |attacker|
		attacker.vm.hostname = "attacker"
		attacker.vm.box = "laravel/homestead"
		attacker.vm.network "private_network", ip: "192.168.50.5", virtualbox__intnet: true
		attacker.vm.synced_folder "./host_shared_folder", "/guest_shared_folder" 
		attacker.vm.provision "shell", inline: <<-SHELL
			pip install unique-id
		SHELL
	end
	config.vm.provider "virtualbox" do |vb|
		vb.name = "attacker"
		vb.gui = false
		vb.memory = "1024"
		vb.cpus = "2"
	end
end
